cvdb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('allauth.urls')),
    path("api-auth/", include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^', include('django.contrib.auth.urls')),
    path("api/01/", include('api01.urls', namespace='api01')),
    path("", include('users.urls')),
    path("", include('viewcv.urls')),
]

viewcv/urls.py
# from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from .upload import UploadCvView, UploadCssView
from .about import AboutView
from .cv import CvOwnList, CvPublicList, CvDetail, CvUpdate, CvSetAsPrimary, CvDelete
from .css import CssList, CssUpdate, CssDelete


urlpatterns = [
    path("u/<slug:username>/", CvDetail.as_view(), name='cv_public'),
    path("css/<int:pk>/edit/", login_required(CssUpdate.as_view()), name='css_update'),
    path("css/<int:pk>/delete/", login_required(CssDelete.as_view()), name='css_delete'),
    path("cv/<int:pk>/set_as_primary/", login_required(CvSetAsPrimary.as_view()), name='cv_set_as_primary'),
    path("cv/<int:pk>/edit/", login_required(CvUpdate.as_view()), name='cv_update'),
    path("cv/<int:pk>/delete/", login_required(CvDelete.as_view()), name='cv_delete'),
    path("cv/<int:pk>/", login_required(CvDetail.as_view()), name='cv'),
    path("upload-css/", login_required(UploadCssView.as_view()), name='upload_css'),
    path("upload/", login_required(UploadCvView.as_view()), name='upload'),
    path("css_list/", CssList.as_view(), name='css_list'),
    path("list/", CvPublicList.as_view(), name='cv_public_list'),
    path("my_cvs/", login_required(CvOwnList.as_view()), name='cv_list'),
    path("about/", AboutView.as_view(), name='about'),
    path("", UploadCvView.as_view(), name='home'),
]

viewcv/models.py
import json
import datetime
from django.db import models
from django.urls import reverse
from django.contrib import auth
from django.utils.translation import gettext_lazy
from viewcv.durations import calculate_duration, duration_as_string


class Css(models.Model):
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.SlugField(max_length=100, default='', verbose_name=gettext_lazy('name'))
    title = models.CharField(max_length=250, blank=True, default='', verbose_name=gettext_lazy('title'))
    summary = models.TextField(blank=True, default='')
    css = models.TextField(blank=True, default='')

    def can_edit(self, user):
        return user == self.creator

    def __str__(self):
        return self.title
        # return '{}:{}'.format(self.name, self.title)


class CssUrl(models.Model):
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.SlugField(max_length=100, default='bootstrap400', verbose_name=gettext_lazy('name'))
    title = models.CharField(max_length=250, blank=True, default='Bootstrap 4.0.0', verbose_name=gettext_lazy('title'))
    summary = models.TextField(blank=True, default='')
    url = models.URLField(max_length=250, blank=True,
                          help_text=gettext_lazy('Link to CSS file'),
                          default='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css')

    def __str__(self):
        return self.title
        # return '{}:{}:{}'.format(self.name, self.title, self.url)


class Cv(models.Model):
    user = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.SlugField(max_length=100, default='default', verbose_name=gettext_lazy('name'))
    title = models.CharField(max_length=250, blank=True, default='', verbose_name=gettext_lazy('title'))
    summary = models.TextField(blank=True, default='')
    public = models.BooleanField(blank=True, default=False,
                                 help_text=gettext_lazy('Are other users allowed to see this CV'))
    primary = models.BooleanField(blank=True, default=False,
                                  help_text=gettext_lazy('Is this the primary CV for this user'))
    css = models.ForeignKey(Css, on_delete=models.SET_NULL, null=True, blank=True, default=None,
                            help_text=gettext_lazy('CSS used for styling CV'))
    css_url = models.ForeignKey(CssUrl, on_delete=models.SET_NULL, null=True, blank=True, default=None,
                                help_text=gettext_lazy('Link to CSS file used for styling CV'))
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    edited = models.DateTimeField(auto_now=True, null=True, blank=True)

    @property
    def personal(self):
        personal = Personal.objects.filter(cv=self)
        if personal.count() == 1:
            return personal.first()
        return None

    @property
    def specialties(self):
        return Skill.objects.filter(cv=self, level='Excellent')

    @property
    def non_specialties(self):
        return Skill.objects.filter(cv=self).exclude(level='Excellent')

    @property
    def hobby_projects(self):
        return Project.objects.filter(cv=self, work=None)

    @property
    def work_projects(self):
        return Project.objects.filter(cv=self).exclude(work=None)

    def can_edit(self, user):
        return user == self.user

    def set_as_primary(self):
        # First make all CVs non-primary, then set this one as primary (so there is only one primary CV)
        if not self.primary:
            Cv.objects.filter(user=self.user).update(primary=False)
            self.primary = True
            self.public = True
            self.save()

    def __str__(self):
        return '{}'.format(self.name)

    def get_absolute_url(self):
        return reverse('cv', args=[self.id])

    class Meta:
        ordering = ['-created']


class Personal(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)
    email = models.EmailField(max_length=200, blank=True, default='')
    phone = models.CharField(max_length=100, blank=True, default='')
    url = models.URLField(max_length=250, blank=True, default='')
    image = models.URLField(max_length=250, blank=True, default='')
    profiles = models.CharField(max_length=1000, blank=True, default='[]')  # Actually a list
    summary = models.TextField(blank=True, default='')

    @property
    def profile_list(self):
        return json.loads(self.profiles)


class Work(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.CharField(max_length=250, blank=True, default='')
    position = models.CharField(max_length=250, blank=True, default='')
    url = models.URLField(max_length=250, blank=True, default='')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    summary = models.TextField(blank=True, default='')

    @property
    def end_date_current(self):  # Replaces end date with current date if not defined
        if self.end_date.year == 1337:
            return datetime.datetime.now()
        return self.end_date

    @property
    def duration(self):
        if self.end_date.year == 1337:
            return calculate_duration(self.start_date, None)
        return calculate_duration(self.start_date, self.end_date)

    @property
    def duration_years(self):
        years, months = self.duration
        return years

    @property
    def duration_months(self):
        years, months = self.duration
        return months

    @property
    def duration_str(self):
        years, months = self.duration
        return duration_as_string(years, months)

    def __str__(self):
        return '{}:{}'.format(self.name, self.position)

    class Meta:
        ordering = ['-start_date']


class Education(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)
    institution = models.CharField(max_length=250, blank=True, default='')
    url = models.URLField(max_length=250, blank=True, default='')
    area = models.CharField(max_length=250, blank=True, default='')
    study_type = models.CharField(max_length=250, blank=True, default='')
    gpa = models.CharField(max_length=50, blank=True, default='')
    summary = models.TextField(blank=True, default='')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    @property
    def end_date_current(self):  # Replaces end date with current date if not defined
        if self.end_date.year == 1337:
            return datetime.datetime.now()
        return self.end_date

    @property
    def duration(self):
        if self.end_date.year == 1337:
            return calculate_duration(self.start_date, None)
        return calculate_duration(self.start_date, self.end_date)

    @property
    def duration_years(self):
        years, months = self.duration
        return years

    @property
    def duration_months(self):
        years, months = self.duration
        return months

    @property
    def duration_str(self):
        years, months = self.duration
        return duration_as_string(years, months)

    def __str__(self):
        return '{}:{}:{}'.format(self.institution, self.area, self.study_type)

    class Meta:
        ordering = ['-start_date']


class Volunteer(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)
    organization = models.CharField(max_length=250, blank=True, default='')
    position = models.CharField(max_length=250, blank=True, default='')
    url = models.URLField(max_length=250, blank=True, default='')
    summary = models.TextField(blank=True, default='')
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    @property
    def end_date_current(self):  # Replaces end date with current date if not defined
        if self.end_date.year == 1337:
            return datetime.datetime.now()
        return self.end_date

    @property
    def duration(self):
        if self.end_date.year == 1337:
            return calculate_duration(self.start_date, None)
        return calculate_duration(self.start_date, self.end_date)

    @property
    def duration_years(self):
        years, months = self.duration
        return years

    @property
    def duration_months(self):
        years, months = self.duration
        return months

    @property
    def duration_str(self):
        years, months = self.duration
        return duration_as_string(years, months)

    def __str__(self):
        return '{}:{}'.format(self.organization, self.position)

    class Meta:
        ordering = ['-start_date']


class Skill(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.CharField(max_length=250, blank=True, default='')
    level = models.CharField(max_length=100, blank=True, default='')
    keywords = models.CharField(max_length=500, blank=True, default='[]')  # Actually a list

    def __str__(self):
        return '{}:{}'.format(self.name, self.level)

    class Meta:
        ordering = ['name']


class Language(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.CharField(max_length=250, blank=True, default='')
    fluency = models.CharField(max_length=100, blank=True, default='')

    def __str__(self):
        return '{}:{}'.format(self.name, self.fluency)


class Project(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE, null=True, blank=True, default=None)

viewcv/views.py
# from django.views.generic.edit import FormView
# from .upload import UploadForm


# class HomeView(FormView):
#    template_name = 'viewcv/home.html'
#    form_class = UploadForm

viewcv/templates/viewcv/snippets/cv_core.html
{% load account %}
{% load i18n %}

<h1> {{ cv.user.first_name }} {{ cv.user.last_name }} &nbsp; <small class="text-muted"> {{ cv.title }} </small> </h1>

{% with info=cv.personal %}
<table class="table table-sm">
  <tbody>
  {% if info.image %}
    <tr>
      <td rowspan="7" style="width:10%">
        <img id="mugshot" alt="{{ user.username }}" src="{{ info.image }}" />
      </td>
    </tr>
  {% endif %}
  {% if info.email %} <tr> <th style="width:20%"> {% trans 'Email' %} </th> <td> {{ info.email }} </td> </tr> {% endif %}
  {% if info.phone %} <tr> <th style="width:20%"> {% trans 'Phone' %} </th> <td> {{ info.phone }} </td> </tr> {% endif %}
  {% if info.url %}
    <tr>
      <th> {% trans 'Home page' %} </th>
      <td> <a href="{{ info.url }}"> {{ info.url }} </a> </td>
    </tr>
  {% endif %}

  {% if cv.specialties.count > 0 %}
    <tr>
      <th> {% trans 'Specialties' %} </th>
      <td>
        {% for skill in cv.specialties.all %}
          {% if forloop.last %}
            {{ skill.name }}
          {% else %}
            {{ skill.name }},
          {% endif %}
        {% endfor %}
      </td>
    </tr>
  {% endif %}

  {% if cv.non_specialties.count > 0 %}
    <tr>
      <th> {% trans 'Other skills' %} </th>
      <td>
        {% for skill in cv.non_specialties.all %}
          {% if forloop.last %}
            {{ skill.name }}
          {% else %}
            {{ skill.name }},
          {% endif %}
        {% endfor %}
      </td>
    </tr>
  {% endif %}

  {% if cv.language_set.count > 0 %}
    <tr>
      <th> Languages </th>
      <td>
        {% for lang in cv.language_set.all %}
          {% if forloop.last %}
            {{ lang.name }}
          {% else %}
            {{ lang.name }},
          {% endif %}
        {% endfor %}
      </td>
    </tr>
  {% endif %}

  {% if info.profile_list %}
    <tr>
      <th> Profiles </th>
      <td>
      {% for profile in info.profile_list %}
        {% if profile.url and profile.username %}
          {{ profile.network }}: <a href="{{ profile.url }}">{{ profile.username }}</a>
        {% else %}
          {{ profile.network }}
        {% endif %}
      {% endfor %}
      </td>
    </tr>
  {% endif %}
  {% if info.summary %}
    <tr> <td colspan="3"> {{ info.summary|safe }} </td> </tr>
  {% endif %}
  </tbody>
</table>
{% endwith %}

<h2 id="work-experience-header"> {%  trans 'Work experience' %} </h2>

<ul>
{% for work in cv.work_set.all %}
  <li> <strong> {{ work.start_date|date:"Y-m" }} /
    {% if work.end_date.year == 1337 %}
      current
    {% else %}
      {{ work.end_date_current|date:"Y-m" }}
    {% endif %}
      ({{ work.duration_str }})
      {{ work.position }} at
    {% if work.url %}
      <a href="{{ work.url }}">{{ work.name }}</a>
    {% else %}
      {{ work.name }}
    {% endif %}
     </strong>
    <ul>
        <li> {{ work.summary }} </li>
    {% if work.project_set.count > 0 and False %}
        <li>
            Projects
            <ul>
        {% for project in work.project_set.all %}
                <li>
            {{ project.start_date|date:"Y-m" }}
            {% if project.duration_str %}
                / {{ project.end_date|date:"Y-m" }}
                ({{ project.duration_str }})
            {% endif %}
            {{ project.name }}
                <ul>
                    <li>{{ project.description }}</li>
                </ul>
        {% endfor %}
            </ul>
        </li>
    {% endif %}
    </ul>
  </li>
{% endfor %}
</ul>

<h2 id="education-header"> {%  trans 'Education' %} </h2>

<ul>
{% for edu in cv.education_set.all %}
  <li> <strong> {{ edu.start_date|date:"Y-m" }} /
    {% if edu.end_date.year == 1337 %}
      ongoing
    {% else %}
      {{ edu.end_date_current|date:"Y-m" }}
    {% endif %}
    ({{ edu.duration_str }})
    {% if edu.study_type and edu.area and edu.institution %}
      {{ edu.study_type }} of {{ edu.area }} at
    {% elif edu.study_type and edu.institution %}
      {{ edu.study_type }} at
    {% elif edu.area and edu.institution %}
      {{ edu.area }} at
    {% endif %}
    {% if edu.url %}
      <a href="{{ edu.url }}">{{ edu.institution }}</a>
    {% else %}
      {{ edu.institution }}
    {% endif %}
   </strong>
    {% if edu.summary %}<ul> <li> {{ edu.summary|safe }} </li> </ul>{% endif %}
  </li>
{% endfor %}
</ul>

{% if cv.volunteer_set.count > 0 %}
<h2 id="volunteer-header"> {%  trans 'Other experience' %} </h2>
<ul>
  {% for vol in cv.volunteer_set.all %}
  <li>
    <strong>
      {{ vol.start_date|date:"Y" }}
    {% if vol.duration_years %}
      / {{ vol.end_date_current|date:"Y" }}
    {% endif %}
      {{ vol.position }} in
    {% if vol.url %}
      <a href="{{ vol.url }}">{{ vol.organization }}</a>
    {% else %}
      {{ vol.organization }}
    {% endif %}
    </strong>
    {% if vol.summary %}
    <ul> <li> {{ vol.summary|safe }} </li> </ul>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endif %}

{% if cv.hobby_projects.count > 0 %}
<h2 id="hobby-projects-header"> {%  trans 'Hobby projects' %} </h2>
<ul>
  {% for project in cv.hobby_projects %}
  <li>
    <strong>
      {{ project.start_date|date:"Y" }}
    {% if vol.duration_years %}
      / {{ project.end_date|date:"Y" }}
    {% endif %}
    {% if project.url %}
      {% if format == 'pdf' %}
        {{ project.name }} ({{ project.url }})
      {% else %}
        <a href="{{ project.url }}">{{ project.name }}</a>
      {% endif %}
    {% else %}
      {{ project.name }}
    {% endif %}
    </strong>
    {% if project.description %}
    <ul>
        {% if project.keyword_str %}
        <li> Technologies: {{ project.keyword_str }}</li>
        {% endif %}
        <li> {{ project.description|safe }} </li>
    </ul>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endif %}

{% if cv.work_projects.count > 0 %}
<h2 id="work-projects-header"> {%  trans 'Work projects' %} </h2>
<ul>
  {% for project in cv.work_projects %}
  <li>
    <strong>
        {{ project.start_date|date:"Y-m" }}
        {% if project.duration_str %}
          {% if project.end_date.year == 1337 %}
            / ongoing
          {% else %}
            / {{ project.end_date_current|date:"Y-m" }}
          {% endif %}
          ({{ project.duration_str }})
        {% endif %}
        {{ project.name }}
    </strong>
    {% if project.description %}
    <ul>
        {% if project.keyword_str %}
        <li> Technologies: {{ project.keyword_str }}</li>
        {% endif %}
        {% if project.industry %}<li>Industry: {{ project.industry }}</li>{% endif %}
        {% if project.client %}<li>Client: {{ project.client }}</li>{% endif %}
        <li>{{ project.description|safe }}</li>
    </ul>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endif %}

viewcv/templates/viewcv/snippets/cv_two_column.html
{% load account %}
{% load i18n %}

<header>
  <h1 id="title-name"> {{ cv.user.first_name }} {{ cv.user.last_name }}</h1>
  <h2 id="cv-title"> {{ cv.title }} </h2>
</header>
<hr />
<aside class="sidebar">
{% with info=cv.personal %}
{% if info.email %}
  <h3>{% trans 'Email' %} </h3>
  <div> {{ info.email }} </div>
{% endif %}
{% if info.phone %}
  <h3>{% trans 'Phone' %}</h3>
  <div> {{ info.phone }} </div>
{% endif %}
{% if info.url %}
  <h3>{% trans 'Home page' %}</h3>
  <div> <a href="{{ info.url }}"> {{ info.url }} </a> </div>
{% endif %}

{% if cv.specialties.count > 0 %}
  <h3>{% trans 'Specialties' %}</h3>
  <div>
    {% for skill in cv.specialties.all %}
      {% if forloop.last %}
        {{ skill.name }}
      {% else %}
        {{ skill.name }},
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

{% if cv.non_specialties.count > 0 %}
  <h3> {% trans 'Other skills' %} </h3>
  <div>
    {% for skill in cv.non_specialties.all %}
      {% if forloop.last %}
        {{ skill.name }}
      {% else %}
        {{ skill.name }},
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

{% if cv.language_set.count > 0 %}
  <h3> Languages </h3>
  <div>
    {% for lang in cv.language_set.all %}
      {% if forloop.last %}
        {{ lang.name }}
      {% else %}
        {{ lang.name }},
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

{% if info.profile_list %}
  <h3> Profiles </h3>
  {% for profile in info.profile_list %}
    {% if profile.url and profile.username %}
      <div>{{ profile.network }}: <a href="{{ profile.url }}">{{ profile.username }}</a></div>
    {% else %}
      <div>{{ profile.network }}</div>
    {% endif %}
  {% endfor %}
  </div>
{% endif %}

{% if info.summary %}
    <div>{{ info.summary|safe }}</div>
{% endif %}
{% endwith %}
</aside>

<main class="main-content">
<h2 id="work-experience-header">{%  trans 'Work experience' %}</h2>

{% for work in cv.work_set.all %}
<h3> {{ work.start_date|date:"Y-m" }} / {{ work.end_date_current|date:"Y-m" }} ({{ work.duration_str }})
      {{ work.position }} at
    {% if work.url %}
      <a href="{{ work.url }}">{{ work.name }}</a>
    {% else %}
      {{ work.name }}
    {% endif %}
</h3>
<div> {{ work.summary }} </div>
  {% if work.project_set.count > 0 and False %}
      <li>
          Projects
          <ul>
      {% for project in work.project_set.all %}
              <li>
          {{ project.start_date|date:"Y-m" }}
          {% if project.duration_str %}
              / {{ project.end_date|date:"Y-m" }}
              ({{ project.duration_str }})
          {% endif %}
          {{ project.name }}
              <ul>
                  <li>{{ project.description }}</li>
              </ul>
      {% endfor %}
            </ul>
        </li>
  {% endif %}
{% endfor %}

<h2 id="education-header"> {%  trans 'Education' %} </h2>

{% for edu in cv.education_set.all %}
  <h3> {{ edu.start_date|date:"Y-m" }} / {{ edu.end_date|date:"Y-m" }} ({{ edu.duration_str }})
    {% if edu.study_type and edu.area and edu.institution %}
      {{ edu.study_type }} of {{ edu.area }} at
    {% elif edu.study_type and edu.institution %}
      {{ edu.study_type }} at
    {% elif edu.area and edu.institution %}
      {{ edu.area }} at
    {% endif %}
    {% if edu.url %}
      <a href="{{ edu.url }}">{{ edu.institution }}</a>
    {% else %}
      {{ edu.institution }}
    {% endif %}
   </h3>
   {% if edu.summary %}<div>{{ edu.summary|safe }}</div>{% endif %}
{% endfor %}

{% if cv.volunteer_set.count > 0 %}
<h2 id="volunteer-header"> {%  trans 'Other experience' %} </h2>
<ul>
  {% for vol in cv.volunteer_set.all %}
  <li>
    <strong>
      {{ vol.start_date|date:"Y" }}
    {% if vol.duration_years %}
      / {{ vol.end_date|date:"Y" }}
    {% endif %}
      {{ vol.position }} in
    {% if vol.url %}
      <a href="{{ vol.url }}">{{ vol.organization }}</a>
    {% else %}
      {{ vol.organization }}
    {% endif %}
    </strong>
    {% if vol.summary %}
    <ul> <li> {{ vol.summary|safe }} </li> </ul>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% endif %}

{% if cv.hobby_projects.count > 0 %}
<h2 id="hobby-projects-header"> {%  trans 'Hobby projects' %} </h2>
  {% for project in cv.hobby_projects %}
    <h3>
      {{ project.start_date|date:"Y" }}
    {% if vol.duration_years %}
      / {{ project.end_date|date:"Y" }}
    {% endif %}
    {% if project.url %}
      <a href="{{ project.url }}">{{ project.name }}</a>
    {% else %}
      {{ project.name }}
    {% endif %}
    </h3>
    {% if project.description %}
    <div>
        {% if project.keyword_str %}
        Technologies: {{ project.keyword_str }}<br />
        {% endif %}
        {{ project.description|safe }}
    </div>
    {% endif %}
  {% endfor %}
{% endif %}

{% if cv.work_projects.count > 0 %}
<h2 id="work-projects-header"> {%  trans 'Work projects' %} </h2>
  {% for project in cv.work_projects %}
    <h3>
        {{ project.start_date|date:"Y-m" }}
    {% if project.duration_str %}
        / {{ project.end_date|date:"Y-m" }}
        ({{ project.duration_str }})
    {% endif %}
    {{ project.name }}
    </h3>
    {% if project.description %}
    <div>
      {% if project.keyword_str %}
        Technologies: {{ project.keyword_str }}<br />
      {% endif %}
      {% if project.industry %}Industry: {{ project.industry }}<br />{% endif %}
      {% if project.client %}Client: {{ project.client }}<br />{% endif %}
      {{ project.description|safe }}
    </div>
    {% endif %}
  {% endfor %}
{% endif %}
</main>